DROP TABLE IF EXISTS usertable CASCADE;
DROP TABLE IF EXISTS questions_answers CASCADE;
DROP TABLE IF EXISTS questionnaire CASCADE;
DROP TABLE IF EXISTS respondent CASCADE;
DROP TABLE IF EXISTS questionrespondent CASCADE;
